name: Update GitHub Stats

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Refresh Stats
        run: |
          curl -s https://github-readme-stats.vercel.app/api?username=maxchichar&show_icons=true&theme=midnight-purple&hide_border=true > stats.svg
          curl -s https://github-readme-streak-stats.herokuapp.com/?user=maxchichar&theme=midnight-purple&hide_border=true > streak.svg

      - name: Commit Stats
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add stats.svg streak.svg
          git commit -m "Update GitHub stats" || echo "No changes"
          git push
